server:
  name: who-sent-api
  version: 1.0.0
  port: :5000
  mode: dev
  readTimeout: 5s
  writeTimeout: 5s
  ssl: false
  ctxDefaultTimeout: 5s
  csrf: true
  debug: true
  maxCountRequest: 100
  expirationLimitTime: 30s

db:
  autoMigrate: false
  postgres:
    host: localhost
    port: 5432
    username: postgres
    password: 123123@Admin
    database: who_sent_db

cache:
  redis:
    mode: standalone
    address:
      - localhost:6379

adapter:
  auth:
    jwtSecret: AXu4VLuQ7XFM7IA
    accessExp: 15m
    refreshExp: 86400m

otherKM:
  defaultRoleId: 1

logConfig:
  level: debug
  encoding: console

