server:
  name: echo-service
  version: 1.0.0
  port: :5000
  mode: dev
  readTimeout: 5s
  writeTimeout: 5s
  ssl: false
  ctxDefaultTimeout: 5s
  csrf: true
  debug: true
  maxCountRequest: 100
  expirationLimitTime: 30s

db:
  autoMigrate: false
  postgres:
    host:
    port:
    username:
    password:
    database:

cache:
  redis:
    mode: standalone
    address:
      - localhost:6379

adapter:
  product:
    host: localhost
    port: 9000
  auth:
    host: localhost
    port: 9005

logConfig:
  level: debug
  encoding: console

